services:
  prettyclose:
    build:
      context: .
      dockerfile: dockerfile
    container_name: prettyclose-prod
    ports:
      - "18000:3000"
    restart: unless-stopped
    volumes:
      - ./files:/usr/src/app/files
      - ./site_static/templates:/usr/src/app/site_static/templates
    networks:
      - prettyclose

networks:
  prettyclose:
    external: true
    name: prettyclose
