services:
  prettyclose:
    build:
      context: .
      dockerfile: dockerfile
    container_name: prettyclose-prod
    ports:
      - "11000:3000"
    restart: unless-stopped
    volumes:
      - ./volumes/app:/app
    networks:
      - prettyclose

networks:
  prettyclose:
    external: true
    name: prettyclose